# Generated by Django 5.0.7 on 2024-08-17 15:49

import django.db.models.deletion
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_drid', models.CharField(blank=True, max_length=255, null=True)),
                ('data_niceid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.IntegerField()),
                ('city_name', models.CharField(max_length=255)),
                ('neighborhood', models.IntegerField(blank=True, null=True)),
                ('neighborhood_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_category', models.IntegerField()),
                ('expertise_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_name_1', models.CharField(max_length=255)),
                ('expertise_name_2', models.CharField(blank=True, max_length=255, null=True)),
                ('nezam_number', models.IntegerField()),
                ('education_level', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to=doctor.models.get_doctor_path)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_link', models.URLField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('office_data', models.JSONField(blank=True, null=True)),
                ('comments_data', models.JSONField(blank=True, null=True)),
                ('social_media', models.JSONField(blank=True, null=True)),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile_url', models.URLField()),
                ('source_page', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=doctor.models.get_doctor_path_for_image)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUrlToScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField(unique=True)),
                ('is_scraped', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_profiles_url_to_scrape', to='doctor.city')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_url_to_scrape', to='doctor.doctor')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neighborhood_profiles_url_to_scrape', to='doctor.neighborhood')),
                ('expertise_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expertise_profiles_url_to_scrape', to='doctor.speciality')),
            ],
        ),
    ]
