# Generated by Django 5.1 on 2024-08-18 14:18

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='office_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=doctor.models.get_doctor_path_for_image),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
