# Generated by Django 5.0.7 on 2024-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='expertise_category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
